import type { ComponentType } from "react";
import * as C from "./components";

export const AppCatalog: Record<string, { component: ComponentType<Record<string, unknown>> }> = {
  Page: { component: C.Page },
  Card: { component: C.Card },
  MetricCard: { component: C.MetricCard },
  List: { component: C.List },
  ListItem: { component: C.ListItem },
  Table: { component: C.Table },
  TableRow: { component: C.TableRow },
  Badge: { component: C.Badge },
  StatusChip: { component: C.StatusChip },
  Button: { component: C.Button },
  Image: { component: C.Image },
  Chart: { component: C.Chart },
  Tabs: { component: C.Tabs },
  Progress: { component: C.Progress },
  Timeline: { component: C.Timeline },
  Alert: { component: C.Alert },
  WeatherCard: { component: C.WeatherCard },
  NewsCard: { component: C.NewsCard },
  TravelCard: { component: C.TravelCard },
  MarketCard: { component: C.MarketCard },
  ProductCard: { component: C.ProductCard },
  InvoiceTable: { component: C.InvoiceTable },
  MilestoneCard: { component: C.MilestoneCard },
  ForecastChart: { component: C.ForecastChart },
  NewsList: { component: C.NewsList },
  FlightCard: { component: C.FlightCard },
  HotelCard: { component: C.HotelCard },
  ProductList: { component: C.ProductList },
  Rating: { component: C.Rating },
  Price: { component: C.Price },
  CompareButton: { component: C.CompareButton },
  CompareTray: { component: C.CompareTray },
  PayButton: { component: C.PayButton },
  OrderCard: { component: C.OrderCard },
  RefundButton: { component: C.RefundButton },
};
